### PR TITLE
Use a compass to find other players

### PR DESCRIPTION
**Pull request by fpigerre**
Hello!

This pull request allows a compass to be used to find other players by
left/right clicking through players.
The code contained within this pull request requires some testing with multiple players in order to ensure that players are selected correctly.

Kind regards,
psgs :palm_tree:

### CODE REVIEW

**Comment by Carlgo11** [comment]
❤️❤️❤️
If you ever get to Sweden I'll buy you dinner for this 😀

**Comment by fpigerre** [comment]
:stuck_out_tongue: If global warming ever gets so bad that Sweden's climate becomes remotely warm, I will definitely take a trip :smiley:

**Comment by Carlgo11** [comment]
Thank you Francois. I just merged your code.

I hope you don't mind that I modified your code a bit.

**Comment by fpigerre** [comment]
No problem :smiley: 
No, I don't mind at all. If there are any bugs with the code I have written or anything else you might want me to help out with, please don't hesitate to let me know.

**Pull request merged**
